
server:
  port: 9010

spring:
  application:
    name: "message"

  cloud:
    function:
      definition: email|sms         # by using this pipe symbol compose both function as single unit.

    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    connectiom-timeout: 10s