apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: tushar601/configserver:s16
          ports:
            - containerPort: 8071
---                                      # these 3 dashes signigy read single yml file into separate 2 yml file
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer                      #expose the container outside the world
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071