
spring:
    application:
        name: "gatewayserver"


    config:
        import: "optional:configserver:http://localhost:8071/"

    cloud:
        gateway:
            httpclient:
                connect-timeout: 1000
                response-timeout: 10s
        kubernetes:
            discovery:
                enabled: true
                all-namespaces: true
        discovery:
            client:
                health-indicator:
                    enabled: false

    data:
        redis:
            connect-timeout: 2s
            host: localhost
            port: 6379
            timeout: 1s
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "http://localhost:7080/realms/master"
                    jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        gateway:
            enabled: true
    info:
        env:
            enabled: true

    metrics:
        tags:
            application: ${spring.application.name}
    logging:
        level:
            com:
                example:
                    gatewayserver: DEBUG

        pattern:
            level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

    resilience4j.circuitbreaker:
        configs:
            default:
                slidingWindowSize: 10
                permittedNumberOfCallsInHalfOpenState: 2
                failureRateThreshold: 50
                waitDurationInOpenState: 10000
info:
    app:
        name: "gatewayserver"
        description: "Eazy bank gateway server application"
        version: "1.0.0"



























#
#spring:
#    application:
#        name: "gatewayserver"
#
#    config:
#        import: "optional:configserver:http://localhost:8071/"
#    cloud:
#        gateway:
#            discovery:
#                locator:
#                    enabled: false                 # for disabling the default routing
#                    lowercase-service-id: true    # allow to give service name in lowercase instead of uppercase in uri
#            httpclient:
#                connect-timeout: 1000
#                response-timeout: 10s
#    data:
#        redis:
#            connect-timeout: 2s
#            host: localhost
#            port: 6379
#            timeout: 1s
#
#    security:
#        oauth2:
#            resourceserver:
#                jwt:
#                    jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
#
#
#
#    app:
#        name: "gatewayserver"
#        description: "EazyBank GatewayServer Application"
#        version: "1.0.0"
#
#management:
#    endpoints:
#        web:
#            exposure:
#                include: "*"
#    metrics:
#        tags:
#            application: ${spring.application.name}
#    endpoint:
#        gateway:
#            enabled: true
#
#logging:
#    level:
#        com:
#            example:
#                gatewayserver: DEBUG
#    pattern:
#        level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
#
#resilience4j.circuitbreaker:
#    configs:
#        default:
#            slidingWindowSize: 10                               # this element tells monitor 10 request atleast before go tho the decision to open or closed status
#            permittedNumberOfCallsInHalfOpenState: 2            #allow 2 request in half open state
#            failureRateThreshold: 50
#            waitDurationInOpenState: 10000
#









#
#rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"




#    config:
#        import:
#            - "application_qa.yml"
#            - "application_prod.yml"
#    profiles:
#        active:
#            - "qa"
#
#
#build:
#    version: "3.O"
#
## here prefix name is accounts
#accounts:
#    message: "Welcome to EazyBank accounts related local APIs"
#    contactDetails:
#        name: "Tushar-Developer"
#        email: "tushar@eazybytes.com"
#    onCallSupport:
#        -(555)555-124
#        -(555)555-125



