
spring:
  application:
    name: "configserver"

  profiles:
    #active: native (native is active only when using classpath and local file system)
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "file:///C://Users//HS965NW//Documents//config"
          #It store the configration file in local system
          #search-locations: "classpath:/config"  (It stores the config files in classpath)
        git:
          uri: "https://github.com/Tushar-ey/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          skip-ssl-validation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

#configure rabbit mq
#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"


server:
  port: 8071
