server:
    port: 8080
spring:
    application:
        name: "accounts"
    profiles:
        active: "prod"
    datasource:
        url: jdbc:mysql://localhost:3307/accountsdb
        username: root
        password: root
    jpa:
        show-sql: true
    sql:
        init:
            mode: always
    config:
        import: "optional:configserver:http://localhost:8071/"

management:
    endpoints:
        web:
            exposure:
                include: "*"

##
#rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"


#    config:
#        import:
#            - "application_qa.yml"
#            - "application_prod.yml"
#    profiles:
#        active:
#            - "qa"
#
#
#build:
#    version: "3.O"
#
## here prefix name is accounts
#accounts:
#    message: "Welcome to EazyBank accounts related local APIs"
#    contactDetails:
#        name: "Tushar-Developer"
#        email: "tushar@eazybytes.com"
#    onCallSupport:
#        -(555)555-124
#        -(555)555-125



