server:
  port: 9001
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3309/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"















#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"



#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profiles:
#    active:
#      - "qa"
#
#build:
#  version: "3.0"
#
#cards:
#  message: "Welcome to EazyBank cards related local APIs "
#  contactDetails:
#    name: "Tushar -Developer"
#    email: "tushar@eazybank.com"
#  onCallSupport:
#    - (412) 419-3491
#    - (915) 382-1932




#springdoc:
#  api-docs:
#    path: /v4/api-docs
#  swagger-ui.path: /swagger-ui.html